import type { Metadata } from "next";
import "@/app/globals.css";
import Navbar from "@/components/navbar";
import AuthProvider from "@/providers/auth-provider";

import { Providers } from "@/redux/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Providers>
            <Navbar />
            {children}
          </Providers>
        </AuthProvider>
      </body>
    </html>
  );
}
